---
AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true
  Exclude:
    - 'control-repo/**/*'
    - 'git/puppet-git-hooks/**/*'

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 110
