---
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  Exclude:
    - 'control-repo/**/*'
    - 'git/puppet-git-hooks/**/*'

Metrics/BlockLength:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: false

Layout/LineLength:
  Max: 110

Style/RegexpLiteral:
  AllowInnerSlashes: true
