---
name: Puppet Toolkit Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Install ShellCheck
        run: |
          curl -L -o /tmp/shellcheck-latest.linux.x86_64.tar.xz https://github.com/koalaman/shellcheck/releases/download/latest/shellcheck-latest.linux.x86_64.tar.xz
          sudo tar -xf /tmp/shellcheck-latest.linux.x86_64.tar.xz --strip-components 1 -C /usr/bin/ shellcheck-latest/shellcheck
      - name: Install PowerShell
        run: |
          pwsh -Command 'Install-Module -Name PSScriptAnalyzer -SkipPublisherCheck -Force'
          pwsh -Command 'Install-Module -Name Pester -SkipPublisherCheck -Force'
      - name: Install Ruby Dependencies
        run: |
          gem install bundler
          bundle install
      - name: Run Tests
        run: |
          bundle exec rake validate 